### ISSUE TITLE
Support Ember 2.10

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/bootstrap-modal#1]
Something with liquid-wormhole/LF, waiting on upstream: https://github.com/pzuraq/liquid-wormhole/issues/21

**Comment by engwan** [comment]
Hi, was this issue resolved?

I tried using the master branch of this plugin but had the same issue. Modal wasn't getting removed because of wormhole.

**Comment by knownasilya** [comment]
Try `npm ls liquid-fire` and `npm ls liquid-wormhole` and print the results here.

**Comment by engwan** [comment]
This was when I used bootstrap-modal 2.1.1:

```
❯ npm ls liquid-wormhole
midash@0.0.1 /home/engwan/Projects/midash-ember
└─┬ bootstrap-modal@2.1.1
  └─┬ liquid-tether@1.1.1
    └── liquid-wormhole@1.1.2 
```

```
 ❯ npm ls liquid-fire    
midash@0.0.1 /home/engwan/Projects/midash-ember
 ├─┬ bootstrap-modal@2.1.1
 │ └── liquid-fire@0.26.5 
 └── liquid-fire@0.26.6 
```

When using master branch, I get `unknown module liquid-tether`. I guess it was removed from the dependencies?

So I manually added `liquid-tether 2.0.0-beta.2` to my package.json.

Here are my packages:

```
❯ npm ls liquid-wormhole
midash@0.0.1 /home/engwan/Projects/midash-ember
├─┬ bootstrap-modal@2.1.1 (git://github.com/knownasilya/bootstrap-modal.git#a849c6df8ea43b5f945784e29eb776b36ac989d9)
│ └── liquid-wormhole@2.0.2 
└─┬ liquid-tether@2.0.0-beta.2
  └── liquid-wormhole@2.0.0-beta.2 
```

Same problem. What version of liquid-tether should I be using?

I also tried using liquid-tether master branch:

```
❯ npm ls liquid-tether
midash@0.0.1 /home/engwan/Projects/midash-ember
└── liquid-tether@2.0.1  (git://github.com/pzuraq/liquid-tether.git#40ce878658a4181d1b6dab5b57342ba717d0fa8f)
```

Upon hiding the modal I get this error:

```
TypeError: Cannot read property 'isVisible' of null
    at Constraint.predicate (<anonymous>:170462:21)
    at Constraints.matchConstraintPredicate (<anonymous>:157032:26)
    at Constraints.matchPredicates (<anonymous>:157011:47)
    at Constraints.match (<anonymous>:156952:22)
    at Constraints.bestMatch (<anonymous>:156933:26)
    at Class.transitionFor (<anonymous>:170137:52)
    at Class.superWrapper [as transitionFor] (<anonymous>:51979:22)
    at Class._transition (<anonymous>:156613:47)
    at Class.childDidRender (<anonymous>:156661:14)
    at Class.send (<anonymous>:52219:35)
```

**Comment by engwan** [comment]
Nevermind, it's working now. The `isVisible` error was caused by something in my `transitions.js`.

But should liquid-tether be added as a dependency?

**Comment by knownasilya** [comment]
No, liquid tether has been removed, since we only used liquid-wormhole any way.
